"""Initial schema creation

Revision ID: afe292643a33
Revises: 
Create Date: 2026-06-11 08:36:52.162250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe292643a33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.String(length=50), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'period_date')
    )
    op.create_index(op.f('ix_macro_indicator_indicator'), 'macro_indicator', ['indicator'], unique=False)
    op.create_index(op.f('ix_macro_indicator_period_date'), 'macro_indicator', ['period_date'], unique=False)
    op.create_table('manual_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'field_name')
    )
    op.create_index(op.f('ix_manual_override_ts_code'), 'manual_override', ['ts_code'], unique=False)
    op.create_table('stock',
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('industry_group', sa.String(length=50), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('is_delisted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('valuation_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=30), nullable=True),
    sa.Column('dcf_intrinsic_bear', sa.Float(), nullable=True),
    sa.Column('dcf_intrinsic_base', sa.Float(), nullable=True),
    sa.Column('dcf_intrinsic_bull', sa.Float(), nullable=True),
    sa.Column('margin_of_safety', sa.Float(), nullable=True),
    sa.Column('red_flags_json', sa.Text(), nullable=True),
    sa.Column('scores_json', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('manual_overrides_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'snapshot_date')
    )
    op.create_index(op.f('ix_valuation_snapshot_snapshot_date'), 'valuation_snapshot', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_valuation_snapshot_ts_code'), 'valuation_snapshot', ['ts_code'], unique=False)
    op.create_table('daily_quote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_factor', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('total_mv', sa.Float(), nullable=True),
    sa.Column('circ_mv', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('turnover_rate_f', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ts_code'], ['stock.ts_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date')
    )
    op.create_index(op.f('ix_daily_quote_trade_date'), 'daily_quote', ['trade_date'], unique=False)
    op.create_index(op.f('ix_daily_quote_ts_code'), 'daily_quote', ['ts_code'], unique=False)
    op.create_index('ix_dq_ts_date', 'daily_quote', ['ts_code', 'trade_date'], unique=False)
    op.create_table('financial_statement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('total_cogs', sa.Float(), nullable=True),
    sa.Column('sell_exp', sa.Float(), nullable=True),
    sa.Column('admin_exp', sa.Float(), nullable=True),
    sa.Column('fin_exp', sa.Float(), nullable=True),
    sa.Column('n_income_attr_p', sa.Float(), nullable=True),
    sa.Column('deducted_profit', sa.Float(), nullable=True),
    sa.Column('minority_int', sa.Float(), nullable=True),
    sa.Column('income_tax', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liab', sa.Float(), nullable=True),
    sa.Column('total_hldr_eqy_exc_min_int', sa.Float(), nullable=True),
    sa.Column('goodwill', sa.Float(), nullable=True),
    sa.Column('intan_assets', sa.Float(), nullable=True),
    sa.Column('other_receiv', sa.Float(), nullable=True),
    sa.Column('inventories', sa.Float(), nullable=True),
    sa.Column('acct_receiv', sa.Float(), nullable=True),
    sa.Column('notes_receiv', sa.Float(), nullable=True),
    sa.Column('acct_payable', sa.Float(), nullable=True),
    sa.Column('money_cap', sa.Float(), nullable=True),
    sa.Column('st_borrow', sa.Float(), nullable=True),
    sa.Column('lt_borrow', sa.Float(), nullable=True),
    sa.Column('fixed_assets', sa.Float(), nullable=True),
    sa.Column('c_fr_oper', sa.Float(), nullable=True),
    sa.Column('c_paid_for_assets', sa.Float(), nullable=True),
    sa.Column('dep_amor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ts_code'], ['stock.ts_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'end_date', 'report_type')
    )
    op.create_index(op.f('ix_financial_statement_end_date'), 'financial_statement', ['end_date'], unique=False)
    op.create_index(op.f('ix_financial_statement_ts_code'), 'financial_statement', ['ts_code'], unique=False)
    op.create_index('ix_fs_ts_end', 'financial_statement', ['ts_code', 'end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fs_ts_end', table_name='financial_statement')
    op.drop_index(op.f('ix_financial_statement_ts_code'), table_name='financial_statement')
    op.drop_index(op.f('ix_financial_statement_end_date'), table_name='financial_statement')
    op.drop_table('financial_statement')
    op.drop_index('ix_dq_ts_date', table_name='daily_quote')
    op.drop_index(op.f('ix_daily_quote_ts_code'), table_name='daily_quote')
    op.drop_index(op.f('ix_daily_quote_trade_date'), table_name='daily_quote')
    op.drop_table('daily_quote')
    op.drop_index(op.f('ix_valuation_snapshot_ts_code'), table_name='valuation_snapshot')
    op.drop_index(op.f('ix_valuation_snapshot_snapshot_date'), table_name='valuation_snapshot')
    op.drop_table('valuation_snapshot')
    op.drop_table('stock')
    op.drop_index(op.f('ix_manual_override_ts_code'), table_name='manual_override')
    op.drop_table('manual_override')
    op.drop_index(op.f('ix_macro_indicator_period_date'), table_name='macro_indicator')
    op.drop_index(op.f('ix_macro_indicator_indicator'), table_name='macro_indicator')
    op.drop_table('macro_indicator')
    # ### end Alembic commands ###
